### ISSUE TITLE
Array_Operations.c

### ISSUE THREAD

**Issue by vivekpenuli** [Hiteshwalia4/Data_and_File_Structures#1]
In this question there is one problem what 
<img width="371" alt="git" src="https://github.com/Hiteshwalia4/Data_and_File_Structures/assets/63710710/b68f85a9-ca55-494a-8d63-e7385bf7bc67">

here we can see when user enter any number except between 1 - 6 it still working . can we restrict the user if he upload any other number except the number between 1- 6.

**Comment by Hiteshwalia4** [comment]
Thanks for pointing the issue, I have added one more else condition in which there is a variable named "noOfAttempts"  that keeps track of the number of attempts if user enters an invalid number. If user exceeds that particular limit, the program will terminate displaying the respective message on screen to make user aware about the termination.
